### ISSUE TITLE
Not all binaries can be called from commandline

### ISSUE THREAD

**Issue by schultyy** [schultyy/avm#36]
When I install this package [https://github.com/sunmille/eslint-to-editorconfig](https://github.com/sunmille/eslint-to-editorconfig)

It can't be called from the commandline:

``` bash
vagrant@localhost:~$ npm install --global eslint-to-editorconfig
/home/vagrant/.avm/bin/eslint-to-editorconfig -> /home/vagrant/.avm/lib/node_modules/eslint-to-editorconfig/bin.js
eslint-to-editorconfig@1.1.0 /home/vagrant/.avm/lib/node_modules/eslint-to-editorconfig
├── colors@1.1.2
└── eslint@1.8.0 (escape-string-regexp@1.0.3, object-assign@2.1.1, path-is-absolute@1.0.0, path-is-inside@1.0.1, xml-escape@1.0.0, user-home@1.1.1, strip-json-comments@1.0.4, estraverse-fb@1.3.1, globals@8.11.0, estraverse@4.1.1, text-table@0.2.0, esutils@2.0.2, to-double-quotes@1.0.2, to-single-quotes@1.0.4, is-resolvable@1.0.0, debug@2.2.0, json-stable-stringify@1.0.0, chalk@1.1.1, shelljs@0.3.0, lodash.merge@3.3.2, optionator@0.5.0, doctrine@0.7.0, mkdirp@0.5.1, lodash.clonedeep@3.0.2, glob@5.0.15, lodash.omit@3.1.0, minimatch@2.0.10, espree@2.2.5, concat-stream@1.5.1, is-my-json-valid@2.12.2, file-entry-cache@1.2.4, inquirer@0.9.0, js-yaml@3.4.3, escope@3.2.0, handlebars@4.0.4)
vagrant@localhost:~$ eslint-to-editorconfig
eslint-to-editorconfig: command not found
vagrant@localhost:~$
```

Right now there's a symlink to the current node version's bin directory. This directory is accessible via `PATH`. It seems that this is not sufficient. nvm has the full path to the current node version's bin directory in the `PATH` variable.

**Comment by schultyy** [comment]
- Tested this in a Vagrant VM (Ubuntu 14.04). All commandline programs are callable.
- Tested this on Mac OS X with zshell. Nothing callable.

**Comment by moonglum** [comment]
Hey @schultyy _waves_

I'm not entirely sure I understand the exact problem: You are saying that in the Vagrant VM all commandline programs are callable, but in the snippet above you are obviously in the VM (or you have a really weird prompt) and `eslint-to-editorconfig` is not callable. Can you explain that again? :smile: 

I justed tried installing this specific NPM package and the binary is callable. I'm using a Vagrant VM, provisioned by an [ansible thingy](https://github.com/moonglum/dotfiles/blob/master/playbooks/nodejs.yml) I wrote.

**Comment by schultyy** [comment]
Ok sorry for the confusion :D

Yesterday evening I tried the thing described above in my Vagrant VM and it worked (Couldn't find out why yet). I tried the same thing on my Mac and there it didn't work. Maybe I just misconfigured something on my machine.

**Comment by moonglum** [comment]
No problem :wink: 

So for me it work[ed|s] like this:
1. Back when I had NPM installed on my Mac, I had the following in my Path: `/usr/local/nodejs/default/bin`. This is where the Node.js I installed via Homebrew put its executables by default.
2. Now that I use NPM in my Ubuntu Vagrant Box, the version I installed via the above mentioned script automatically links all executables into `/usr/local/bin`, which is in the path by default.

Maybe this helps?

**Comment by schultyy** [comment]
Hmm, I thought the issue is zsh, so I installed it into an Ubuntu VM and tried to call the commandline tool again and it works. So I guess the problem is more related to my machine.

**Comment by schultyy** [comment]
I figured out this was an issue on my local machine :facepalm:

**Comment by moonglum** [comment]
Yay, fixed :dancers:

**Comment by schultyy** [comment]
🙆🏽
